language: python

env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110
    - TOX_ENV=py35-django18
    - TOX_ENV=py35-django19
    - TOX_ENV=py35-django110

install: pip install codecov tox tox-travis

script: tox -e $TOX_ENV

after_success:
    - codecov -e $TOX_ENV

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
